<a href="https://colab.research.google.com/github/timlok123/Learning-the-basic-of-AI-with-Python/blob/main/Ch6_Possible_problems_and_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ch6 - Possible problem in AI training and Solution

In [1]:
import numpy as np
import matplotlib.pyplot as plt

(List the possible problems & solution encountered during training AI network)

## Neural network training

### Introduction

In the following of the notebook, we are using the *Iris flower dataset* for training.
(Explanation on the data, the components of data, no of data)

(The structure of the AI model, activation function & output layer function in between, optimization methods and loss function, batch size, test case,  )

### Data preparation

Below are the steps of data preparation,

1. Load the data from *sklearn* module
2. Normalization
3. Convert the label for training (Understand why do we need to do this)
4. Split the train and test case

In [14]:
from sklearn import datasets

iris_data = datasets.load_iris()
input_data = iris_data.data
correct = iris_data.target

no_of_data = len(correct)

In [15]:
# Print the first 10 data & take a look of the data
print(input_data[:10,])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [13]:
# Normalization
mean_col = np.mean(input_data,axis=0)
std_col = np.std(input_data,axis=0)
normalized_data = (input_data - mean_col)/(std_col)

Turn the `correct` to one-hot labelling (Add the graph of one-hot labelling scheme & why do we need to turn it to one-hot)

In [17]:
# Turn the `correct` to one-hot labelling
correct_data = np.zeros((no_of_data,3),dtype=int)

# TODO: Figure out a way to make use the vectorization
for i in range(no_of_data):
    correct_data[i][correct[i]] = 1


In [19]:
# Split the data to test & learn case
from sklearn.model_selection import train_test_split

input_train, intpu_test, correct_train, correct_test = train_test_split(
    normalized_data,
    correct_data,
    test_size=no_of_data//2
)

### Network structure

1. Define the hyperparameters & initial vaules for the network
2. Define the layer structure as object
3. Forward and back propagation definition


### Training procedures